Update tuner to allow single value parameters
alteryx/evalml pull request #1686
Opened 2021-01-12 19:46 UTC by bchen1116

first step to solve #1625

2021-01-12 21:02 UTC, bchen1116 commented on evalml/tests/tuner_tests/test_skopt_tuner.py
> -    print(random_state)
remove unnecessary print statements

2021-01-12 22:52 UTC, chukarsten commented
It seems you have a exception in grid_search_tuner that is uncovered by some of the tests you dropped.  It's only one line but you can find it in the codecov.io coverage changes.

2021-01-12 22:55 UTC, chukarsten approved these changes

2021-01-12 22:56 UTC, chukarsten requested changes
I think you might just need to address the uncovered exception and this is gucci.

2021-01-13 14:29 UTC, jeremyliweishih approved these changes
Looks great to me but could you add coverage making sure that the tuners can `propose` with single values as well?

2021-01-13 21:11 UTC, chukarsten approved these changes
Nice, thanks!

2021-01-13 21:26 UTC, merged