Datetime support for 1-way Partial Dependence
alteryx/evalml pull request #2454
Opened 2021-06-28 22:08 UTC by bchen1116

fix #2385

2021-06-29 16:01 UTC, bchen1116 commented on evalml/tests/model_understanding_tests/test_partial_dependence.py
> +        return
This test takes about 1 min to run locally.

2021-07-09 18:18 UTC, chukarsten requested changes
Nice job overcoming the issue and getting the performance increase.  I think you're definitely on the right track, but I do have some concerns about using the sklearn private functions as well as duplicating some of the code in sklearn's partial_dependence().  I'd like to explore maybe modifying the data so that you can send it into the stock part_dep function and then perhaps fix it after it comes out.  Not sure if that's a good solution, though so would be happy to pair on it.

2021-07-09 18:18 UTC, chukarsten commented on evalml/model_understanding/graphs.py
> +            ).values.reshape(-1, 1)
I like this, I think it's clever.  Converting to seconds after Unix time, yes?  So ultimately your using a large integer number to compute the grid.  Perhaps we can use this calculation to replace the dates with seconds after unix time, run the data through sklearn's stock partial dependence, then convert the datetime feature back after the fact?  To me, I think that would mitigate some of the code duplication and use of private funcs issues.

2021-07-13 19:38 UTC, bchen1116 commented
@chukarsten filed an issue to track fixing/cleaning this up [here](https://github.com/alteryx/evalml/issues/2502)

2021-07-13 19:52 UTC, freddyaboulton approved these changes
@bchen1116 Thanks for doing this! The speed-up looks fantastic. I left some suggestions for adding test coverage. Definitely agree that the next step is to clean up our partial dependence - possible roll our own implementation!

2021-07-13 19:54 UTC, bchen1116 commented on evalml/pipelines/components/transformers/preprocessing/datetime_featurizer.py
> +                # if is_numeric_dtype(X[col_name].dtype):
Good catch!

2021-07-13 22:20 UTC, bchen1116 commented on evalml/tests/model_understanding_tests/test_partial_dependence.py
> +        return
@freddyaboulton The entire test takes about 1 minute locally! Leaving the grid and size unconstrained makes it run much longer

2021-07-13 22:25 UTC, bchen1116 commented on evalml/model_understanding/graphs.py
> +                [X_dt - pd.Timestamp("1970-01-01")] // np.timedelta64(1, "s")
@freddyaboulton updated the tests!

2021-07-13 22:29 UTC, freddyaboulton commented on evalml/model_understanding/graphs.py
> +                [X_dt - pd.Timestamp("1970-01-01")] // np.timedelta64(1, "s")
Thanks @bchen1116 Looks good to me! Is the runtime reasonable?

2021-07-14 16:56 UTC, bchen1116 commented on evalml/model_understanding/graphs.py
> +                [X_dt - pd.Timestamp("1970-01-01")] // np.timedelta64(1, "s")
@freddyaboulton It takes less than 20 seconds locally to run

2021-07-15 00:00 UTC, merged