Add documentation for using ComponentGraphs
alteryx/evalml pull request #2673
Opened 2021-08-23 16:56 UTC by angela97lin

Closes #2367

2021-08-30 14:07 UTC, eccabay requested changes
This looks great! I left a couple requests for small new sections.

The biggest thing missing for me is discussion of the flow of a graph, as was mentioned in the original issue. I would love to see a section talking about compute order, and how to know what components to link together and how. There's a little bit of that implicitly shown in the larger example, but it would be great to have a whole section dedicated to discussing it.

2021-08-30 14:07 UTC, eccabay commented on docs/source/user_guide/component_graphs.ipynb
> +    "You can use `.get_component(name)` and provide the unique component name to access any component in the component graph. Below, we can grab our Imputer component and confirm that `numeric_impute
Can you add a section about `get_inputs` here as well?

2021-08-30 14:07 UTC, eccabay commented on docs/source/user_guide/component_graphs.ipynb
> +    "EvalML component graphs represent and describe the flow of data in a collection of related components. A component graph is comprised of nodes representing components, and edges between pairs of
Maybe add a link to a description of what a DAG is here, for anyone unfamiliar with graph theory

2021-08-30 19:21 UTC, bchen1116 approved these changes
Agreed with Becca's comments, but looks good!

2021-08-30 19:21 UTC, bchen1116 commented on docs/source/user_guide/component_graphs.ipynb
> +    "Each component can have a number of feature inputs (identified as \"X\" or ending in \".x\"), but can only have one target input (identified as \"y\" or ending in \".y\"). All input edges must b
Could be useful to have an example of what it looks like to have multiple X inputs

2021-09-01 18:43 UTC, angela97lin commented on docs/source/user_guide/component_graphs.ipynb
> +    "Component graphs can be defined by specifying the dictionary of components and edges that describe the graph. In this dictionary, each key is the name that should be used to reference a componen
I love this, thank you for the context!

(Long sentences have always been my weakness, thank you for helping me break it down 😁)

2021-09-05 00:32 UTC, chukarsten approved these changes
Looks solid to me! Thank you!

2021-09-05 00:32 UTC, merged