Select Smarter Lags for Time Series
alteryx/evalml pull request #3005
Opened 2021-11-02 22:23 UTC by freddyaboulton

### Pull Request Description
Fixes #2733 

-----
*After creating the pull request: in order to pass the **release_notes_updated** check you will need to update the "Future Release" section of* `docs/source/release_notes.rst` *to include this pull request by adding :pr:`123`.*

2021-11-03 14:10 UTC, freddyaboulton commented on evalml/tests/component_tests/test_delayed_features_transformer.py
> +            max_delay=3, gap=0, forecast_horizon=1, conf_level=1.0
Using a `conf_level` of 1.0 selects all lags. Some of these tests rely on the DelayedFeatureTransformer selecting all lags.

2021-11-03 17:00 UTC, bchen1116 requested changes
Great work on this! You got this out so fast. I think one thing that we should add before merging this would be some documentation, maybe [here](https://evalml.alteryx.com/en/stable/user_guide/timeseries.html), that would allow users to understand what this component is doing and how changing conf_level could change the lags used. This would help with un-black-boxing the component.

Otherwise, left some nits and some questions. Good stuff though!

2021-11-03 17:33 UTC, freddyaboulton commented on evalml/pipelines/components/transformers/preprocessing/delayed_feature_transformer.py
> +        conf_level (float, None): Float between 0 and 1 that determines the confidence interval size used to select
Absolutely. Will get rid of the outdated `None` as well as adding some validation that conf_level is in the range (0, 1].

2021-11-03 17:35 UTC, freddyaboulton commented on evalml/pipelines/components/transformers/preprocessing/delayed_feature_transformer.py
> +            first_significant_10 = index[:10][significant[:10]]
Yea I can see why this is confusing now. The intention is to select the significant lags in the range [0, 10] not the first 10 significant lags.

2021-11-03 17:43 UTC, freddyaboulton commented on evalml/pipelines/components/transformers/preprocessing/delayed_feature_transformer.py
> +            selects all possible lags in the set of [1, max_delay], inclusive.
Good catch. Added some parameter validation as well.

2021-11-03 17:49 UTC, freddyaboulton commented on evalml/tests/component_tests/test_delayed_features_transformer.py
> +        set(significant_lags + peaks).intersection(peaks).union(first_significant_10)
Yep, making this change now!

2021-11-03 18:59 UTC, freddyaboulton commented
@bchen1116 Added details on the algorithm to the component docstring and added a link from the user guide to the component reference since I didn't want to jump deep into the specifics of a component in the user guide. Thanks for the feedback though, the documentation definitely needed improvement.

2021-11-04 15:01 UTC, ParthivNaresh approved these changes
Looks good! In your perf tests it showed that `Daily Female Births` had slightly lower validation results while `Southern Oscillations` had slightly better. It would be interesting to see how Prophet and ARIMA perform (once we enable DelayedFeatureTransformer for ARIMA).

2021-11-04 16:03 UTC, freddyaboulton commented on evalml/pipelines/components/transformers/preprocessing/delayed_feature_transformer.py
> +        if conf_level is not None and y is not None:
I think what happened originally I set the default value to `None` to mean "no lags" but that doesn't work well with our tuners so I made it be a float. I'll move the none check to the init! Thank you.

2021-11-04 16:12 UTC, bchen1116 approved these changes
LGTM! Thanks for making the changes! Agreed with @ParthivNaresh about `conf_level=None`, but other than that, great work!

2021-11-04 17:34 UTC, merged