Rename TextFeaturizer to NaturalLanguageFeaturizer
alteryx/evalml pull request #3030
Opened 2021-11-09 20:52 UTC by jeremyliweishih

Fixes #2914.

2021-11-11 22:11 UTC, eccabay requested changes
This looks great! It's encouraging to me how simple of a change this is.

I have two main things moving forward:
- There's a few other places in the documentation that should be updated to add the new primitives: the explanatory part of the text tutorial [here](https://evalml.alteryx.com/en/stable/demos/text_input.html#What-does-the-Text-Featurization-Component-do?) as well as the docstring where it lists the primitives (marked in another comment)
- I'm very interested to see how the performance tests change with this update. I did a bunch of performance testing way back when originally adding this component to determine the best primitives to use, and I know there were some I explicitly removed to improve performance. I hope these will reflect real improvement!

Other than that, just left a couple small nits. Looks great though!

2021-11-11 22:11 UTC, eccabay commented on evalml/pipelines/components/transformers/preprocessing/natural_language_featurizer.py
> +class NaturalLanguageFeaturizer(TextTransformer):
Can you add the new primitives to the list in the docstring?

2021-11-12 15:40 UTC, freddyaboulton approved these changes
@jeremyliweishih Thanks for this! I think this looks good. For completeness we may want to rename TextTransformer to NaturalLanguageTransformer but I don't think that's a hard requirement to close out this issue.

2021-11-12 15:40 UTC, freddyaboulton commented on docs/source/release_notes.rst
> +        * Added ``NumWords`` and ``NumCharacters`` primitives to ``TextFeaturizer`` and renamed ``TextFeaturizer` to ``NaturalLanguageFeaturizer`` :pr:`3030`
nit-pick: Move to next release section.

2021-11-12 16:02 UTC, jeremyliweishih commented
Will update with perf tests soon!

2021-11-12 16:21 UTC, eccabay approved these changes
Looks great! Looking forward to seeing the perf test results.

2021-11-12 19:14 UTC, jeremyliweishih commented
@eccabay uploaded the perf test results in the description. Lmk what you think!

2021-11-12 21:49 UTC, merged