Updated data check code for regression
alteryx/evalml pull request #3630
Opened 2022-07-27 19:52 UTC by simha104

### Pull Request Description
(replace this text with your description)

-----
*After creating the pull request: in order to pass the **release_notes_updated** check you will need to update the "Future Release" section of* `docs/source/release_notes.rst` *to include this pull request by adding :pr:`123`.*

2022-07-28 14:54 UTC, chukarsten requested changes
Thanks for making the adjustment!  I think we should still adjust the name, though.

2022-07-28 14:54 UTC, chukarsten commented on evalml/data_checks/data_check_message_code.py
> +    TARGET_REGRESSION_NON_NUMERIC = "target_regression_non_numeric"
Maybe we just rename this to `TARGET_UNSUPPORTED_TYPE_REGRESSION`?  As named, it doesn't seem to get the point across to me.  Also a nit: "incompatible with regression"

2022-07-28 15:26 UTC, bchen1116 approved these changes
Agreed with Karsten here, but looks good otherwise.

2022-07-29 18:37 UTC, chukarsten approved these changes
Thanks a bunch!

2022-07-29 18:37 UTC, merged