Add `dates_needed_for_prediction_range`
alteryx/evalml pull request #3941
Opened 2023-01-19 19:25 UTC by jeremyliweishih

2023-01-24 01:20 UTC, chukarsten approved these changes
I think just need to update the docstring!

2023-01-24 01:20 UTC, chukarsten commented on evalml/pipelines/time_series_pipeline_base.py
> +            raise ValueError("`start_date` must come before `end_date`.")
Just a nit, but we've had a `Raises:` section in the docstring.

2023-01-24 15:12 UTC, eccabay requested changes
The code looks great! I think the addition to the docs needs a bit of clarification, it's hard to understand exactly what the goal is with it.

2023-01-24 15:12 UTC, eccabay commented on docs/source/user_guide/timeseries.ipynb
> +   "source": []
This is an empty cell!

2023-01-24 15:12 UTC, eccabay commented on docs/source/user_guide/timeseries.ipynb
> +    "tags": []
This cell feels out of place to me, I'm not quite sure why it's here. Is it supposed to be somewhere else?

2023-01-24 15:12 UTC, eccabay commented on evalml/tests/pipeline_tests/test_time_series_pipeline.py
> +    assert end_date < prediction_end
Just for future understanding's sake, could you add a comment here explaining what we're testing?

2023-01-26 15:18 UTC, eccabay approved these changes
Looks good! The documentation is much easier to understand. Just a couple typos, but otherwise let's 🚢

2023-01-26 15:18 UTC, eccabay commented on docs/source/user_guide/timeseries.ipynb
> +    "Our previous examples of shown using a pipeline to predict data we had at training time. However, we can also use EvalML time series pipelines to forecast dates into the future as long we provid
Typo: "examples of shown" -> "examples have shown". Also maybe "to predict data we had at training time" -> "to predict *on* data we had at training time"

2023-01-26 15:18 UTC, eccabay commented on docs/source/user_guide/timeseries.ipynb
> +   "source": []
It's still here 👀

2023-01-26 16:50 UTC, merged