Add SMAPE metric
alteryx/evalml pull request #4220
Opened 2023-06-30 21:09 UTC by remyogasawara

Resolves #4218

2023-07-03 17:12 UTC, eccabay requested changes
Looks awesome! Just a few metric-specific details that should be ironed out before merge.

2023-07-03 17:12 UTC, eccabay commented on evalml/objectives/standard_metrics.py
> +        if (y_true == 0).any():
Looks like sMAPE is slightly more flexible with 0 values than MAPE is - there will only be an error if both `y_pred` and `y_true` are 0. We should allow users to use this metric in that case.

For testing purposes, there should be a case with only 0s in `y_pred`, only 0s in `y_true`, and 0s in both

2023-07-03 17:12 UTC, eccabay commented on evalml/tests/objective_tests/test_objectives.py
> +            pytest.skip("MAPE and SMAPE doesn't support inputs containing 0")
Tiny nitpick: doesn't -> don't 😅

2023-07-03 19:57 UTC, remyogasawara commented on evalml/objectives/standard_metrics.py
> +    expected_range = [0, float("inf")]
yep, my bad

2023-07-03 21:05 UTC, eccabay approved these changes
Awesome job!

2023-07-05 18:03 UTC, christopherbunn approved these changes

2023-07-05 18:03 UTC, merged