extended time series regularizer
alteryx/evalml pull request #4303
Opened 2023-09-11 21:52 UTC by MichaelFu512

### Pull Request Description
Extended time series regularizer

-----
*After creating the pull request: in order to pass the **release_notes_updated** check you will need to update the "Future Release" section of* `docs/source/release_notes.rst` *to include this pull request by adding :pr:`123`.*

2023-09-11 21:53 UTC, machineFL commented
No linked issues found. Please add the corresponding issues in the pull request description. <br/> [Use GitHub automation to close the issue when a PR is merged](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) <!-- metadata = {"action":"linked_issue"} -->

2023-09-12 21:29 UTC, MichaelFu512 commented on evalml/pipelines/components/transformers/preprocessing/time_series_regularizer.py
> +                y_dates[self.time_index] = X[self.time_index]
Can y_unstacked have a column for time index or should it not?

2023-09-13 14:22 UTC, eccabay requested changes
We're going to need more testing, but the impl itself is solid!

2023-09-13 14:22 UTC, eccabay commented on evalml/tests/component_tests/test_time_series_regularizer.py
> +def test_ts_regularizer_multiseries(multiseries_ts_data_unstacked, missing):
I think we need more robust testing here - there are more scenarios that will need the regularizer than just missing values. Can you parametrize the existing tests to cover the multiseries case?

2023-09-14 15:09 UTC, jeremyliweishih approved these changes
Quick refactor but otherwise LGTM.

2023-09-14 17:54 UTC, christopherbunn approved these changes

2023-09-14 18:03 UTC, eccabay approved these changes
A few small comments, but nothing blocking. The tests are much cleaner now, thank you!

2023-09-14 18:03 UTC, eccabay commented on evalml/tests/component_tests/test_time_series_regularizer.py
> +    reg_y["target_1"] = [int(i) for i in range(len(dates), 0, -1)]
You can simplify all the `[int(i) for i in range(<params>)]` to be just `list(range(<params>))`!

2023-09-14 18:03 UTC, eccabay commented on evalml/tests/component_tests/test_time_series_regularizer.py
> +def check(is_multiseries, X, y, X_output, y_output, error_dict):
Can the function name be slightly more descriptive? It's not immediately obvious *what* is being checked here

2023-09-14 18:54 UTC, merged