Update split_data to call split_multiseries_data
alteryx/evalml pull request #4312
Opened 2023-09-18 20:26 UTC by eccabay

Closes #4311

2023-09-18 21:14 UTC, jeremyliweishih requested changes
Some quick comments but otherwise LGTM

2023-09-18 21:14 UTC, jeremyliweishih commented on evalml/preprocessing/utils.py
> +        series_id = problem_configuration.get("series_id")
Should check if problem_configuration exists and key exists before getting and if not also raise the same value error.

2023-09-18 21:14 UTC, jeremyliweishih commented on evalml/tests/preprocessing_tests/test_split_data.py
> +            pytest.skip("Multiseries time series is tested separately")
Instead of skipping could we mock out the multi series split and asset that it's called?

2023-09-18 21:46 UTC, MichaelFu512 approved these changes

2023-09-19 16:36 UTC, christopherbunn approved these changes

2023-09-19 17:12 UTC, merged